"""Add Users model

Revision ID: d7941749a79b
Revises: 201da28017f0
Create Date: 2023-03-08 21:01:26.484776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7941749a79b'
down_revision = '201da28017f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
